### ISSUE TITLE
Missing version change inside shard.yml on tag v0.2.2

### ISSUE THREAD

**Issue by faustinoaq** [crystal-community/jwt#14]
Hi @veelenga @greyblake 

Can you re-release/re-publish/re-create tag v0.2.2 because it doesn't include v0.2.2 on shard.yml, see:

https://github.com/crystal-community/jwt/commit/49f0edb296bc267e41918235df6e8da222ea12d7

and 

https://github.com/crystal-community/jwt/blob/v0.2.2/shard.yml#L2

This causes problems with `shards install` because dependencies will be always broken:

```
...
Installing jwt (0.1.0 at 0.2.2)
...
```

See: https://github.com/crystal-lang/shards/issues/183

**Comment by veelenga** [comment]
Published a new release https://github.com/crystal-community/jwt/releases/tag/v0.2.3
