### ISSUE TITLE
Error: undefined method 'final' for OpenSSL::Digest

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [crystal-community/jwt#34]
![image](https://user-images.githubusercontent.com/12284806/84703623-f14e0500-af2e-11ea-95e6-7012cd5844dc.png)

In lib/jwt/src/jwt.cr:126:75

**Comment by stakach** [comment]
https://crystal-lang.org/api/0.35.0/Digest/Base.html#final:Bytes-instance-method

I think it's new to crystal 0.35
